# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: py_client.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpy_client.proto\x12\x02pb\"\x99\x01\n\x07Request\x12\x19\n\x0cregistration\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x02id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08inputUrl\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x17\n\noutputPath\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x0f\n\r_registrationB\x05\n\x03_idB\x0b\n\t_inputUrlB\r\n\x0b_outputPath\"P\n\x08Response\x12\x13\n\x06status\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\toutputUrl\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_statusB\x0c\n\n_outputUrl\",\n\rUploadRequest\x12\x0c\n\x04mime\x18\x01 \x01(\t\x12\r\n\x05\x63hunk\x18\x02 \x01(\x0c\"\x1e\n\x0eUploadResponse\x12\x0c\n\x04name\x18\x01 \x01(\t2x\n\rClientRequest\x12*\n\x0bSendRequest\x12\x0b.pb.Request\x1a\x0c.pb.Response\"\x00\x12;\n\x0eUploadToServer\x12\x11.pb.UploadRequest\x1a\x12.pb.UploadResponse\"\x00(\x01\x42\x06Z\x04./pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'py_client_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _REQUEST._serialized_start=24
  _REQUEST._serialized_end=177
  _RESPONSE._serialized_start=179
  _RESPONSE._serialized_end=259
  _UPLOADREQUEST._serialized_start=261
  _UPLOADREQUEST._serialized_end=305
  _UPLOADRESPONSE._serialized_start=307
  _UPLOADRESPONSE._serialized_end=337
  _CLIENTREQUEST._serialized_start=339
  _CLIENTREQUEST._serialized_end=459
# @@protoc_insertion_point(module_scope)
