# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import py_signc_pb2 as py__signc__pb2


class SigningRequestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendRequest = channel.unary_unary(
                '/pb.SigningRequest/SendRequest',
                request_serializer=py__signc__pb2.SignRequest.SerializeToString,
                response_deserializer=py__signc__pb2.SignResponse.FromString,
                )
        self.UploadToServer = channel.stream_unary(
                '/pb.SigningRequest/UploadToServer',
                request_serializer=py__signc__pb2.UploadRequest.SerializeToString,
                response_deserializer=py__signc__pb2.UploadResponse.FromString,
                )


class SigningRequestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendRequest(self, request, context):
        """Sends a signing request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadToServer(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SigningRequestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRequest,
                    request_deserializer=py__signc__pb2.SignRequest.FromString,
                    response_serializer=py__signc__pb2.SignResponse.SerializeToString,
            ),
            'UploadToServer': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadToServer,
                    request_deserializer=py__signc__pb2.UploadRequest.FromString,
                    response_serializer=py__signc__pb2.UploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.SigningRequest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SigningRequest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.SigningRequest/SendRequest',
            py__signc__pb2.SignRequest.SerializeToString,
            py__signc__pb2.SignResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadToServer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/pb.SigningRequest/UploadToServer',
            py__signc__pb2.UploadRequest.SerializeToString,
            py__signc__pb2.UploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
